### ISSUE TITLE
Add Oauth2 Token Exchange Flow

### ISSUE THREAD

**Issue by nikzen** [famedly/synapse-token-authenticator#26]
### Description
To be able to integrate into existent projects we need to be able to consume OAuth2 Tokens.

### Solution
We add another flow which is called com.famedly.login.token.oauth which is able to accept OAuth2 Access Tokens as a Payload. It verifies the token using introspection and returns a matrix access token.

https://www.notion.so/famedly/OAuth2-Token-Exchange-8e0dffb7618f4978a601129d42e8333a

```[tasklist]
### Tasks
- [x] Refactor configuration to account for multiple flows
- [x] Return the login type com.famedly.login.token.oauth
- [x] Add the endpoint GET /_matrix/client/v3/login/com.famedly.login.oauth to return issuer & issuer-metadata
- [x] Validate the JWT
- [x] Verify the access token using oauth2 introspection endpoint
- [x] Return Matrix Access Token on success
- [x] Add organization ID to GET request to login method
- [x] Implement Error Handling & Logging
- [x] Add Plugin to Synapse Deployment & Update Test Instance with IDP
- [x] Test the implementation with a client
- [ ] Document everything
```
